name: Build and publish documents

on:
  push:
  schedule:
    - cron: "42 23 * * 6" # At 23:42 every saturday.

jobs:
  build_publish_documents_job:
    name: Build and publish documents job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Pull docker image
        run: |
          docker pull osbm/osbm-cv:latest

      - name: Build
        run: |
          docker run --rm -v $(pwd):/data osbm/osbm-cv xelatex resume.tex

      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: resume.pdf

      - name: Move files to the publish directory
        run: mkdir github_deploy && mv resume.pdf github_deploy/resume.pdf

      - name: Deploy the pdf file
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build-${{ github.ref_name }}
          force_orphan: true
