name: Build and publish documents

on:
  push:
  schedule:
    - cron: "42 23 * * 6" # At 23:42 every saturday.

jobs:
  build_publish_documents_job:
    name: Build and publish documents job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install nix action
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: |
          nix build
          mv result resume.pdf

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.pdf

      - name: Move files to the publish directory
        run: mkdir github_deploy && mv resume.pdf github_deploy/resume.pdf

      - name: Deploy the pdf file
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build-${{ github.ref_name }}
          force_orphan: true
